# Generated by Django 5.0.4 on 2024-04-25 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите вопрос', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='TestTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название теста', max_length=64, verbose_name='Название или тема тестов')),
                ('description', models.TextField(help_text='Введите описание или тему текста', verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Введите ответ', max_length=255, verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, help_text='Выберите правильный ответ', verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='apps.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='apps.testtopic'),
        ),
    ]
